name: py311-apple-sphinx
channels:
  - apple
dependencies:
  - python=3.11.3
  - pip>=23.1.0
  - pip:
    - Sphinx>=6.2.1
    - sphinxcontrib-bibtex>=2.5.0
    - sphinxcontrib-applehelp>=1.0.4
    - sphinxcontrib-htmlhelp>=2.0.1
    - piccolo-theme>=0.15.0
    - lxml>=4.9.2
    - setuptools-git-versioning>=1.9.2
    - ruff>=0.0.271
    - yapf>=0.33.0
    - isort>=5.12.0
    - pytest>=7.3.1
    - pytest-cov>=4.1.0
